version: "3.9"
services:
  nodeapi:
    build: 
      context: .
      args:
      - APP_USER=eliasjunior  # or APP_USER=nginx for production 
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "8080:8080"
    
  reactimg:
    build:
      context: ../home-video
      dockerfile: "../home-video/Dockerfile"
    ports:
      - "80:80"
    restart: always
  