version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
  nginx:
    build:
      context: ../home-video
      dockerfile: ../home-video/Dockerfile
    ports:
      - "80:80"
    restart: always
  